### ISSUE TITLE
not receiving sentry errors

### ISSUE THREAD

**Issue by SET001** [arabold/serverless-sentry-lib#14]
having this configuration in `serverless.yml`:

```
plugins:
  - serverless-sentry
  - serverless-appsync-plugin
custom:
  sentry:
    dsn: https://xxxxxx@cccc/ssss
    environment: prod
    project: ens
```

and this simple lambda that should throw an error:

```
const Raven = require('raven');
const RavenLambdaWrapper = require('serverless-sentry-lib'); // This helper library

module.exports.handler = RavenLambdaWrapper.handler(Raven, async (event, context) => {
  // Raven.config('https://xxxxxx@cccc/ssss').install();
  console.log('!!!!', asdasd.aasd.aaa);
  return { message: 'Go Serverless! Your function executed successfully!', event };
});
```
I do not receive errors in sentry, unless I uncoment `Raven.config('https://xxxxxx@cccc/ssss').install();` line. In both cases I'm getting this warning when lambda invoked:

```
Sentry disabled in local environment
raven@2.6.4 alert: no DSN provided, error reporting disabled
```

I'm testing this by invoking lambda locally `sls invoke local -f retry`.  What am I doing wrong?

**Comment by omarkdev** [comment]
Hello,

First you need to disable the local filter to be able to catch the errors in development, to do this just put in your serverless.yml `filterLocal: false`, in your case the result is:

```
custom:
  sentry:
    dsn: https://xxxxxx@cccc/ssss
    environment: prod
    project: ens
    filterLocal: false
```

Second, what you are returning in your handler its a message of success, you need to return an error. To return an error, as you are not using the callback, just throw an exception, or if you prefer to use the callback, just pass as the first argument of the callback.
