### ISSUE TITLE
filterLocal doesn't seem to work

### ISSUE THREAD

**Issue by luqmaan** [arabold/serverless-sentry-lib#8]
I tried using the `filterLocal` custom option but could not get it to work.

```
plugins:
  - serverless-content-encoding
  - serverless-sentry

custom:
  contentEncoding:
    minimumCompressionSize: 0
  sentry:
    dsn: ${env:SENTRY_DSN}
    filterLocal: false
```

The only way I could get [`pluginConfig.filterLocal`](https://github.com/arabold/serverless-sentry-lib/blob/a4f5e7fe052776593b4882ba6e4dba9e69aed1e9/index.js#L84) to be `false` was by setting the environment variable `SENTRY_FILTER_LOCAL=false`.

```
SENTRY_FILTER_LOCAL=false SLS_DEBUG='*' serverless invoke local -f emailreset
````
